/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.jpac.plc.s7.symaddr.parser;

import org.jpac.plc.s7.symaddr.node.*;
import org.jpac.plc.s7.symaddr.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTStructsym(@SuppressWarnings("unused") TStructsym node)
    {
        this.index = 0;
    }

    @Override
    public void caseTStructendsym(@SuppressWarnings("unused") TStructendsym node)
    {
        this.index = 1;
    }

    @Override
    public void caseTVarsym(@SuppressWarnings("unused") TVarsym node)
    {
        this.index = 2;
    }

    @Override
    public void caseTBool(@SuppressWarnings("unused") TBool node)
    {
        this.index = 3;
    }

    @Override
    public void caseTByte(@SuppressWarnings("unused") TByte node)
    {
        this.index = 4;
    }

    @Override
    public void caseTChar(@SuppressWarnings("unused") TChar node)
    {
        this.index = 5;
    }

    @Override
    public void caseTWord(@SuppressWarnings("unused") TWord node)
    {
        this.index = 6;
    }

    @Override
    public void caseTDword(@SuppressWarnings("unused") TDword node)
    {
        this.index = 7;
    }

    @Override
    public void caseTInt(@SuppressWarnings("unused") TInt node)
    {
        this.index = 8;
    }

    @Override
    public void caseTDint(@SuppressWarnings("unused") TDint node)
    {
        this.index = 9;
    }

    @Override
    public void caseTReal(@SuppressWarnings("unused") TReal node)
    {
        this.index = 10;
    }

    @Override
    public void caseTString(@SuppressWarnings("unused") TString node)
    {
        this.index = 11;
    }

    @Override
    public void caseTUdt(@SuppressWarnings("unused") TUdt node)
    {
        this.index = 12;
    }

    @Override
    public void caseTS5time(@SuppressWarnings("unused") TS5time node)
    {
        this.index = 13;
    }

    @Override
    public void caseTTime(@SuppressWarnings("unused") TTime node)
    {
        this.index = 14;
    }

    @Override
    public void caseTTimeofday(@SuppressWarnings("unused") TTimeofday node)
    {
        this.index = 15;
    }

    @Override
    public void caseTDate(@SuppressWarnings("unused") TDate node)
    {
        this.index = 16;
    }

    @Override
    public void caseTDateandtime(@SuppressWarnings("unused") TDateandtime node)
    {
        this.index = 17;
    }

    @Override
    public void caseTArray(@SuppressWarnings("unused") TArray node)
    {
        this.index = 18;
    }

    @Override
    public void caseTOf(@SuppressWarnings("unused") TOf node)
    {
        this.index = 19;
    }

    @Override
    public void caseTComma(@SuppressWarnings("unused") TComma node)
    {
        this.index = 20;
    }

    @Override
    public void caseTColon(@SuppressWarnings("unused") TColon node)
    {
        this.index = 21;
    }

    @Override
    public void caseTSemicolon(@SuppressWarnings("unused") TSemicolon node)
    {
        this.index = 22;
    }

    @Override
    public void caseTDot(@SuppressWarnings("unused") TDot node)
    {
        this.index = 23;
    }

    @Override
    public void caseTDotdot(@SuppressWarnings("unused") TDotdot node)
    {
        this.index = 24;
    }

    @Override
    public void caseTLParen(@SuppressWarnings("unused") TLParen node)
    {
        this.index = 25;
    }

    @Override
    public void caseTRParen(@SuppressWarnings("unused") TRParen node)
    {
        this.index = 26;
    }

    @Override
    public void caseTLSquarebracket(@SuppressWarnings("unused") TLSquarebracket node)
    {
        this.index = 27;
    }

    @Override
    public void caseTRSquarebracket(@SuppressWarnings("unused") TRSquarebracket node)
    {
        this.index = 28;
    }

    @Override
    public void caseTIdentifier(@SuppressWarnings("unused") TIdentifier node)
    {
        this.index = 29;
    }

    @Override
    public void caseTSign(@SuppressWarnings("unused") TSign node)
    {
        this.index = 30;
    }

    @Override
    public void caseTNumber(@SuppressWarnings("unused") TNumber node)
    {
        this.index = 31;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 32;
    }
}
