/**
* PROJECT   : jpac sample project
* MODULE    : UDT_Test_Array2D.java 
* VERSION   : $Revision$
* DATE      : $Date$
* PURPOSE   : implements the S7 data item UDT_Test_Array2D
* REMARKS   : this code was automatically generated by the struct generator
*             of the jPAC S7 communication library
* LOG       : $Log$
*
* The jPac S7 communication library is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* The jPac S7 communication library is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with the jPac S7 communication library. If not, see <http://www.gnu.org/licenses/>.
*
*/

package org.jpac.s7.sample;

import org.jpac.IndexOutOfRangeException;
import org.jpac.plc.AddressException;
import org.jpac.plc.Connection;
import org.jpac.plc.Address;
import org.jpac.plc.Data;
import org.jpac.plc.LobRxTx;
import org.jpac.plc.BitRxTx;

public class UDT_Test_Array2D extends LobRxTx{

    private BitRxTx[][] 		Feld2D;

    //constructor for standalone use
    public UDT_Test_Array2D(Connection conn, Address address) throws IndexOutOfRangeException{
        super(conn, address, 0, null);
        setData(conn.generateDataObject(getSize()));
    }

    //constructor for use inside a structure
    public UDT_Test_Array2D(Connection conn, Address address, int dataOffset, Data data) throws IndexOutOfRangeException{
        super(conn, address, dataOffset, data);
    }

    protected void assertIndexRange(int IndexNumber, int setFirstIndex, int setLastIndex, int actualIndex) throws IndexOutOfRangeException{
        if (actualIndex < setFirstIndex || actualIndex > setLastIndex)
            throw new IndexOutOfRangeException("expecting [" + setFirstIndex + ".." + setLastIndex + "] for index" + IndexNumber + ", found: " + actualIndex);
    }

    public static int getSize(){
        return 4;
    }


    @SuppressWarnings("empty-statement")
    public BitRxTx getFeld2D(int index1 ,int index2) throws AddressException, IndexOutOfRangeException{

        assertIndexRange(1, 1, 3, index1);
        assertIndexRange(2, 1, 5, index2);

        if (Feld2D == null){
            Feld2D = new BitRxTx[3][5];
        }
        //check, if the item already has been accessed
        if (Feld2D[index1 - 1][index2 - 1] == null){
            //if not, instantiate a new representation
            //and store it for subsequent uses
            int dimSize2 = 1;
            int byteOffset = getAddress().getByteIndex() + 0 + (index1 - 1)*dimSize2 + (index2 - 1) / 8;
            Address addr = null;
            try{addr = (Address)getAddress().clone();}catch(CloneNotSupportedException exc){};
            addr.setByteIndex(byteOffset);
            addr.setBitIndex((index2 - 1) % 8);
            addr.setSize(BitRxTx.getSize());
            Feld2D[index1 - 1][index2 - 1] = new BitRxTx(getConnection(), addr, byteOffset, getData());
        }
        return Feld2D[index1 - 1][index2 - 1];
    }
}
