/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.jpac.plc.s7.symaddr.node;

import org.jpac.plc.s7.symaddr.analysis.*;

@SuppressWarnings("nls")
public final class AArraydim extends PArraydim
{
    private PSignednumber _firstindex_;
    private TDotdot _dotdot_;
    private PSignednumber _lastindex_;

    public AArraydim()
    {
        // Constructor
    }

    public AArraydim(
        @SuppressWarnings("hiding") PSignednumber _firstindex_,
        @SuppressWarnings("hiding") TDotdot _dotdot_,
        @SuppressWarnings("hiding") PSignednumber _lastindex_)
    {
        // Constructor
        setFirstindex(_firstindex_);

        setDotdot(_dotdot_);

        setLastindex(_lastindex_);

    }

    @Override
    public Object clone()
    {
        return new AArraydim(
            cloneNode(this._firstindex_),
            cloneNode(this._dotdot_),
            cloneNode(this._lastindex_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArraydim(this);
    }

    public PSignednumber getFirstindex()
    {
        return this._firstindex_;
    }

    public void setFirstindex(PSignednumber node)
    {
        if(this._firstindex_ != null)
        {
            this._firstindex_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._firstindex_ = node;
    }

    public TDotdot getDotdot()
    {
        return this._dotdot_;
    }

    public void setDotdot(TDotdot node)
    {
        if(this._dotdot_ != null)
        {
            this._dotdot_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dotdot_ = node;
    }

    public PSignednumber getLastindex()
    {
        return this._lastindex_;
    }

    public void setLastindex(PSignednumber node)
    {
        if(this._lastindex_ != null)
        {
            this._lastindex_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lastindex_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._firstindex_)
            + toString(this._dotdot_)
            + toString(this._lastindex_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._firstindex_ == child)
        {
            this._firstindex_ = null;
            return;
        }

        if(this._dotdot_ == child)
        {
            this._dotdot_ = null;
            return;
        }

        if(this._lastindex_ == child)
        {
            this._lastindex_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._firstindex_ == oldChild)
        {
            setFirstindex((PSignednumber) newChild);
            return;
        }

        if(this._dotdot_ == oldChild)
        {
            setDotdot((TDotdot) newChild);
            return;
        }

        if(this._lastindex_ == oldChild)
        {
            setLastindex((PSignednumber) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
