/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.jpac.plc.s7.symaddr.node;

import org.jpac.plc.s7.symaddr.analysis.*;

@SuppressWarnings("nls")
public final class AArrayType extends PType
{
    private PArraydecl _arraydecl_;

    public AArrayType()
    {
        // Constructor
    }

    public AArrayType(
        @SuppressWarnings("hiding") PArraydecl _arraydecl_)
    {
        // Constructor
        setArraydecl(_arraydecl_);

    }

    @Override
    public Object clone()
    {
        return new AArrayType(
            cloneNode(this._arraydecl_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArrayType(this);
    }

    public PArraydecl getArraydecl()
    {
        return this._arraydecl_;
    }

    public void setArraydecl(PArraydecl node)
    {
        if(this._arraydecl_ != null)
        {
            this._arraydecl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._arraydecl_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._arraydecl_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._arraydecl_ == child)
        {
            this._arraydecl_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._arraydecl_ == oldChild)
        {
            setArraydecl((PArraydecl) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
