/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.jpac.plc.s7.symaddr.node;

import org.jpac.plc.s7.symaddr.analysis.*;

@SuppressWarnings("nls")
public final class ADateType extends PType
{
    private TDate _date_;

    public ADateType()
    {
        // Constructor
    }

    public ADateType(
        @SuppressWarnings("hiding") TDate _date_)
    {
        // Constructor
        setDate(_date_);

    }

    @Override
    public Object clone()
    {
        return new ADateType(
            cloneNode(this._date_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADateType(this);
    }

    public TDate getDate()
    {
        return this._date_;
    }

    public void setDate(TDate node)
    {
        if(this._date_ != null)
        {
            this._date_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._date_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._date_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._date_ == child)
        {
            this._date_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._date_ == oldChild)
        {
            setDate((TDate) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
