/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.jpac.plc.s7.symaddr.node;

import org.jpac.plc.s7.symaddr.analysis.*;

@SuppressWarnings("nls")
public final class ADateandtimeType extends PType
{
    private TDateandtime _dateandtime_;

    public ADateandtimeType()
    {
        // Constructor
    }

    public ADateandtimeType(
        @SuppressWarnings("hiding") TDateandtime _dateandtime_)
    {
        // Constructor
        setDateandtime(_dateandtime_);

    }

    @Override
    public Object clone()
    {
        return new ADateandtimeType(
            cloneNode(this._dateandtime_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADateandtimeType(this);
    }

    public TDateandtime getDateandtime()
    {
        return this._dateandtime_;
    }

    public void setDateandtime(TDateandtime node)
    {
        if(this._dateandtime_ != null)
        {
            this._dateandtime_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dateandtime_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._dateandtime_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._dateandtime_ == child)
        {
            this._dateandtime_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._dateandtime_ == oldChild)
        {
            setDateandtime((TDateandtime) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
