/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.jpac.plc.s7.symaddr.node;

import org.jpac.plc.s7.symaddr.analysis.*;

@SuppressWarnings("nls")
public final class AMultipleArraydimList extends PArraydimList
{
    private PArraydimList _arraydimList_;
    private TComma _comma_;
    private PArraydim _arraydim_;

    public AMultipleArraydimList()
    {
        // Constructor
    }

    public AMultipleArraydimList(
        @SuppressWarnings("hiding") PArraydimList _arraydimList_,
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PArraydim _arraydim_)
    {
        // Constructor
        setArraydimList(_arraydimList_);

        setComma(_comma_);

        setArraydim(_arraydim_);

    }

    @Override
    public Object clone()
    {
        return new AMultipleArraydimList(
            cloneNode(this._arraydimList_),
            cloneNode(this._comma_),
            cloneNode(this._arraydim_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultipleArraydimList(this);
    }

    public PArraydimList getArraydimList()
    {
        return this._arraydimList_;
    }

    public void setArraydimList(PArraydimList node)
    {
        if(this._arraydimList_ != null)
        {
            this._arraydimList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._arraydimList_ = node;
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PArraydim getArraydim()
    {
        return this._arraydim_;
    }

    public void setArraydim(PArraydim node)
    {
        if(this._arraydim_ != null)
        {
            this._arraydim_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._arraydim_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._arraydimList_)
            + toString(this._comma_)
            + toString(this._arraydim_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._arraydimList_ == child)
        {
            this._arraydimList_ = null;
            return;
        }

        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._arraydim_ == child)
        {
            this._arraydim_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._arraydimList_ == oldChild)
        {
            setArraydimList((PArraydimList) newChild);
            return;
        }

        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._arraydim_ == oldChild)
        {
            setArraydim((PArraydim) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
