/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.jpac.plc.s7.symaddr.node;

import org.jpac.plc.s7.symaddr.analysis.*;

@SuppressWarnings("nls")
public final class AS5timeType extends PType
{
    private TS5time _s5time_;

    public AS5timeType()
    {
        // Constructor
    }

    public AS5timeType(
        @SuppressWarnings("hiding") TS5time _s5time_)
    {
        // Constructor
        setS5time(_s5time_);

    }

    @Override
    public Object clone()
    {
        return new AS5timeType(
            cloneNode(this._s5time_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAS5timeType(this);
    }

    public TS5time getS5time()
    {
        return this._s5time_;
    }

    public void setS5time(TS5time node)
    {
        if(this._s5time_ != null)
        {
            this._s5time_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._s5time_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._s5time_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._s5time_ == child)
        {
            this._s5time_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._s5time_ == oldChild)
        {
            setS5time((TS5time) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
