/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.jpac.plc.s7.symaddr.node;

import org.jpac.plc.s7.symaddr.analysis.*;

@SuppressWarnings("nls")
public final class AStructType extends PType
{
    private PStruct _struct_;

    public AStructType()
    {
        // Constructor
    }

    public AStructType(
        @SuppressWarnings("hiding") PStruct _struct_)
    {
        // Constructor
        setStruct(_struct_);

    }

    @Override
    public Object clone()
    {
        return new AStructType(
            cloneNode(this._struct_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStructType(this);
    }

    public PStruct getStruct()
    {
        return this._struct_;
    }

    public void setStruct(PStruct node)
    {
        if(this._struct_ != null)
        {
            this._struct_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._struct_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._struct_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._struct_ == child)
        {
            this._struct_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._struct_ == oldChild)
        {
            setStruct((PStruct) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
