/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.jpac.plc.s7.symaddr.node;

import org.jpac.plc.s7.symaddr.analysis.*;

@SuppressWarnings("nls")
public final class AStringType extends PType
{
    private PStringdecl _stringdecl_;

    public AStringType()
    {
        // Constructor
    }

    public AStringType(
        @SuppressWarnings("hiding") PStringdecl _stringdecl_)
    {
        // Constructor
        setStringdecl(_stringdecl_);

    }

    @Override
    public Object clone()
    {
        return new AStringType(
            cloneNode(this._stringdecl_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStringType(this);
    }

    public PStringdecl getStringdecl()
    {
        return this._stringdecl_;
    }

    public void setStringdecl(PStringdecl node)
    {
        if(this._stringdecl_ != null)
        {
            this._stringdecl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._stringdecl_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._stringdecl_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._stringdecl_ == child)
        {
            this._stringdecl_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._stringdecl_ == oldChild)
        {
            setStringdecl((PStringdecl) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
