/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.jpac.plc.s7.symaddr.node;

import org.jpac.plc.s7.symaddr.analysis.*;

@SuppressWarnings("nls")
public final class ATimeofdayType extends PType
{
    private TTimeofday _timeofday_;

    public ATimeofdayType()
    {
        // Constructor
    }

    public ATimeofdayType(
        @SuppressWarnings("hiding") TTimeofday _timeofday_)
    {
        // Constructor
        setTimeofday(_timeofday_);

    }

    @Override
    public Object clone()
    {
        return new ATimeofdayType(
            cloneNode(this._timeofday_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATimeofdayType(this);
    }

    public TTimeofday getTimeofday()
    {
        return this._timeofday_;
    }

    public void setTimeofday(TTimeofday node)
    {
        if(this._timeofday_ != null)
        {
            this._timeofday_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._timeofday_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._timeofday_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._timeofday_ == child)
        {
            this._timeofday_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._timeofday_ == oldChild)
        {
            setTimeofday((TTimeofday) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
