/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.jpac.plc.s7.symaddr.node;

import org.jpac.plc.s7.symaddr.analysis.*;

@SuppressWarnings("nls")
public final class AVar extends PVar
{
    private TVarsym _varsym_;
    private PVariablesDefinitionList _variablesDefinitionList_;

    public AVar()
    {
        // Constructor
    }

    public AVar(
        @SuppressWarnings("hiding") TVarsym _varsym_,
        @SuppressWarnings("hiding") PVariablesDefinitionList _variablesDefinitionList_)
    {
        // Constructor
        setVarsym(_varsym_);

        setVariablesDefinitionList(_variablesDefinitionList_);

    }

    @Override
    public Object clone()
    {
        return new AVar(
            cloneNode(this._varsym_),
            cloneNode(this._variablesDefinitionList_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVar(this);
    }

    public TVarsym getVarsym()
    {
        return this._varsym_;
    }

    public void setVarsym(TVarsym node)
    {
        if(this._varsym_ != null)
        {
            this._varsym_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varsym_ = node;
    }

    public PVariablesDefinitionList getVariablesDefinitionList()
    {
        return this._variablesDefinitionList_;
    }

    public void setVariablesDefinitionList(PVariablesDefinitionList node)
    {
        if(this._variablesDefinitionList_ != null)
        {
            this._variablesDefinitionList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._variablesDefinitionList_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._varsym_)
            + toString(this._variablesDefinitionList_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._varsym_ == child)
        {
            this._varsym_ = null;
            return;
        }

        if(this._variablesDefinitionList_ == child)
        {
            this._variablesDefinitionList_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._varsym_ == oldChild)
        {
            setVarsym((TVarsym) newChild);
            return;
        }

        if(this._variablesDefinitionList_ == oldChild)
        {
            setVariablesDefinitionList((PVariablesDefinitionList) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
