/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.jpac.plc.s7.symaddr.node;

import org.jpac.plc.s7.symaddr.analysis.*;

@SuppressWarnings("nls")
public final class AVariablesDefinition extends PVariablesDefinition
{
    private PVariablesTypeAssignment _variablesTypeAssignment_;
    private TSemicolon _semicolon_;

    public AVariablesDefinition()
    {
        // Constructor
    }

    public AVariablesDefinition(
        @SuppressWarnings("hiding") PVariablesTypeAssignment _variablesTypeAssignment_,
        @SuppressWarnings("hiding") TSemicolon _semicolon_)
    {
        // Constructor
        setVariablesTypeAssignment(_variablesTypeAssignment_);

        setSemicolon(_semicolon_);

    }

    @Override
    public Object clone()
    {
        return new AVariablesDefinition(
            cloneNode(this._variablesTypeAssignment_),
            cloneNode(this._semicolon_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVariablesDefinition(this);
    }

    public PVariablesTypeAssignment getVariablesTypeAssignment()
    {
        return this._variablesTypeAssignment_;
    }

    public void setVariablesTypeAssignment(PVariablesTypeAssignment node)
    {
        if(this._variablesTypeAssignment_ != null)
        {
            this._variablesTypeAssignment_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._variablesTypeAssignment_ = node;
    }

    public TSemicolon getSemicolon()
    {
        return this._semicolon_;
    }

    public void setSemicolon(TSemicolon node)
    {
        if(this._semicolon_ != null)
        {
            this._semicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semicolon_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._variablesTypeAssignment_)
            + toString(this._semicolon_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._variablesTypeAssignment_ == child)
        {
            this._variablesTypeAssignment_ = null;
            return;
        }

        if(this._semicolon_ == child)
        {
            this._semicolon_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._variablesTypeAssignment_ == oldChild)
        {
            setVariablesTypeAssignment((PVariablesTypeAssignment) newChild);
            return;
        }

        if(this._semicolon_ == oldChild)
        {
            setSemicolon((TSemicolon) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
